name: Update release notes preview
permissions: read-all

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_START_TIME:  2024-10-23T07:37:53Z
  PRE_RELEASE_TAG:   0.83.0-alpha
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_RELEASE_DRAFTER }}

jobs:
  update_release_notes:
    runs-on: ubuntu-latest
    if: github.repository == 'dosbox-staging/dosbox-staging'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Query pull requests
        run: |
          ./scripts/tools/release-notes-drafter.py query \
              -p pull-requests.csv -s $RELEASE_START_TIME

      - name: Generate release notes
        run: |
          ./scripts/tools/release-notes-drafter.py process \
              -i pull-requests.csv -m release-notes.md

      - name: Publish release notes preview
        run: |
          ./scripts/tools/release-notes-drafter.py publish \
              -n release-notes.md -t $PRE_RELEASE_TAG

